apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-data
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "C:\\Users\\secop\\Desktop\\data\\db"